### ISSUE TITLE
Signup with e-mail fails with duplicate error

### ISSUE THREAD

**Issue by mateherber** [kdrag0n/hueflake-issues#1]
Hi 👋🏻 !

I'd like to register with e-mail and password combination and it fails with a following screen:
![image](https://user-images.githubusercontent.com/13942888/196526010-abe2e52f-caf8-4367-a816-2177d619c829.png)

E-mail: `<redacted for privacy>@kagamirai.dev`

**Comment by kdrag0n** [comment]
Applied a temporary fix for now. Thanks for reporting!

**Comment by kdrag0n** [comment]
Now fixed permanently.
