### ISSUE TITLE
Cannot change public to private or vice-verse on edit page

### ISSUE THREAD

**Issue by mateherber** [kdrag0n/hueflake-issues#2]
Even having a subscription, I'm not able to switch between private and public on the edit page. (I can achieve the result I want on the three dotted menu on the theme page though)

![image](https://user-images.githubusercontent.com/13942888/196993984-04b3616b-da3f-4fb9-8a59-719c0f1241cc.png)

**Comment by kdrag0n** [comment]
Fixed, thanks!
