### ISSUE TITLE
Suggestion: Be able to set the brightness of "white" text color for dark backgrounds

### ISSUE THREAD

**Issue by mateherber** [kdrag0n/hueflake-issues#3]
![image](https://user-images.githubusercontent.com/13942888/196994332-7a1dec13-4fe2-4276-b6f0-fd34086554ca.png)

The brightness of the "white" text can't be changed without raising brightness / increasing contrast which messes with the other colors too. It would be nice to modify that white brightness without affecting all of the other colors.

Reason: As the white is usually off-grey I find it really hard to differentiate in IntelliJ between "white" text and "unused" things marked grey.

**Comment by kdrag0n** [comment]
Do you have an example of where white text and unused are hard to distinguish in IntelliJ?

**Comment by mateherber** [comment]
Hmm. While trying to reproduce this issue I see enough contrast between the disabled and white font but while coding I sometimes I wished the "white" color was whiter. I'll add two samples where contrast is not super working for my eyes but I think we can close this now.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/13942888/198340350-9e7ec52b-dac5-4643-95b0-7a102ab93722.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/13942888/198340467-c78d0b4b-f672-4b9f-91fb-5dc411594fd9.png">

**Comment by kdrag0n** [comment]
That's fair. I'll see what I can do and possibly increase the default white contrast.
